spring:
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false

  security:
    user:
      name: admin
      password: 1234

  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        default_batch_fetch_size: 1000
  output:
    ansi:
      enabled: always

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 250MB
  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss

server:
  error:
    include-stacktrace: never
  tomcat:
    max-http-form-post-size: 200MB
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log


token:
  refresh-token-header: RefreshToken
  roles: roles
  secret: aG5nc2lodDM4N3locndzYW9ocmY4OWFyeWhnM3c5Z3Izd3E4eXI4dzN5aHJvOXczcg==
  access-token-expiration: 10800000 # 3?? ?????
  refresh-token-expiration: 259200000 # 3? ?????

