spring:
  sql:
    init:
      mode: never # always, never, embedded 더미 데이터를 넣을 때 사용(개발할 때만 사용)
  jpa:
    hibernate:
      ddl-auto: create # create, update, validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: false # 더미 데이터를 넣을 때 사용(개발할 때만 사용)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_reference?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: dev_user
    password: dev_user@2024
  servlet:
    multipart:
      location: C:/reference/backend/upload
      max-file-size: 200MB
      max-request-size: 250MB

logging:
  pattern:
    level: DEBUG
  file:
    path: C:/reference/backend/logs/





